# Generated by Django 4.0.5 on 2022-06-14 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCampeonato', models.CharField(max_length=30)),
                ('nombreAuspiciante', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del equipo')),
                ('siglas', models.CharField(max_length=30, verbose_name='Siglas')),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('posicion', models.CharField(max_length=30, unique=True)),
                ('nroCamiseta', models.CharField(max_length=30, unique=True)),
                ('sueldo', models.CharField(max_length=30)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losjugadores', to='futbolec.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=200)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loscampeonatos', to='futbolec.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loscampeonatos', to='futbolec.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='campeonato',
            name='equipos',
            field=models.ManyToManyField(through='futbolec.CampeonatoE', to='futbolec.equipo'),
        ),
    ]
